num=int(input("give a numbers :"))
 #print("before reverse your number is :%d " %num)  
print("before reverse your number is :",num)
rev = int(str(num)[::-1])
print("after reverse the number is : ",rev)